package com.smarthospital.core.export;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.*;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class PdfExportUtil {

    private PdfExportUtil() {}

    public static byte[] build(String title, List<String> headers,
                               List<List<Object>> rows, String generatedBy) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4.rotate());
            PdfWriter.getInstance(doc, out);
            doc.open();

            // Title
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16, Color.decode("#1677ff"));
            Paragraph titlePara = new Paragraph("SmartHospital — " + title, titleFont);
            titlePara.setAlignment(Element.ALIGN_CENTER);
            doc.add(titlePara);

            // Meta
            Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 9, Color.GRAY);
            Paragraph meta = new Paragraph(
                "Generated by: " + generatedBy + "   |   " +
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm")),
                metaFont);
            meta.setAlignment(Element.ALIGN_CENTER);
            meta.setSpacingAfter(12);
            doc.add(meta);

            // Table
            PdfPTable table = new PdfPTable(headers.size());
            table.setWidthPercentage(100);

            // Header cells
            for (String h : headers) {
                PdfPCell cell = new PdfPCell(new Phrase(h,
                        FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, Color.WHITE)));
                cell.setBackgroundColor(Color.decode("#1677ff"));
                cell.setPadding(6);
                table.addCell(cell);
            }

            // Data cells (alternating row colour)
            boolean alternate = false;
            for (List<Object> rowData : rows) {
                Color bg = alternate ? Color.decode("#f0f2f5") : Color.WHITE;
                for (Object val : rowData) {
                    PdfPCell cell = new PdfPCell(new Phrase(
                            val != null ? val.toString() : "",
                            FontFactory.getFont(FontFactory.HELVETICA, 8)));
                    cell.setBackgroundColor(bg);
                    cell.setPadding(4);
                    table.addCell(cell);
                }
                alternate = !alternate;
            }

            doc.add(table);

            // Footer
            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 8, Color.GRAY);
            Paragraph footer = new Paragraph("© SmartHospital Management System", footerFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(20);
            doc.add(footer);

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF export", e);
        }
    }
}
